/**
 * Types of system notifications
 */
export enum NotificationType {
  NEW_MESSAGE = 'NEW_MESSAGE',
  HIGH_PRIORITY_ALERT = 'HIGH_PRIORITY_ALERT',
  TASK_DUE = 'TASK_DUE',
  CALENDAR_REMINDER = 'CALENDAR_REMINDER',
  COMMITMENT_DETECTED = 'COMMITMENT_DETECTED',
  SYSTEM_STATUS = 'SYSTEM_STATUS'
}
